# Regression Predict Student Solution

© Explore Data Science Academy

---
### Honour Code

I {**YOUR NAME, YOUR SURNAME**}, confirm - by submitting this document - that the solutions in this notebook are a result of my own work and that I abide by the [EDSA honour code](https://drive.google.com/file/d/1QDCjGZJ8-FmJE3bZdIQNwnJyQKPhHZBn/view?usp=sharing).

Non-compliance with the honour code constitutes a material breach of contract.

### Predict Overview: Spain Electricity Shortfall Challenge

The government of Spain is considering an expansion of it's renewable energy resource infrastructure investments. As such, they require information on the trends and patterns of the countries renewable sources and fossil fuel energy generation. Your company has been awarded the contract to:

- 1. analyse the supplied data;
- 2. identify potential errors in the data and clean the existing data set;
- 3. determine if additional features can be added to enrich the data set;
- 4. build a model that is capable of forecasting the three hourly demand shortfalls;
- 5. evaluate the accuracy of the best machine learning model;
- 6. determine what features were most important in the model’s prediction decision, and
- 7. explain the inner working of the model to a non-technical audience.

Formally the problem statement was given to you, the senior data scientist, by your manager via email reads as follow:

> In this project you are tasked to model the shortfall between the energy generated by means of fossil fuels and various renewable sources - for the country of Spain. The daily shortfall, which will be referred to as the target variable, will be modelled as a function of various city-specific weather features such as `pressure`, `wind speed`, `humidity`, etc. As with all data science projects, the provided features are rarely adequate predictors of the target variable. As such, you are required to perform feature engineering to ensure that you will be able to accurately model Spain's three hourly shortfalls.
 
On top of this, she has provided you with a starter notebook containing vague explanations of what the main outcomes are.

<a id="cont"></a>

## Table of Contents

<a href=#one>1. Importing Packages</a>

<a href=#two>2. Loading Data</a>

<a href=#three>3. Exploratory Data Analysis (EDA)</a>

<a href=#four>4. Data Engineering</a>

<a href=#five>5. Modeling</a>

<a href=#six>6. Model Performance</a>

<a href=#seven>7. Model Explanations</a>

 <a id="one"></a>
## 1. Importing Packages
<a href=#cont>Back to Table of Contents</a>

---
    
| ⚡ Description: Importing Packages ⚡ |
| :--------------------------- |
| In this section you are required to import, and briefly discuss, the libraries that will be used throughout your analysis and modelling. |

---

In [2]:
# Libraries for data loading, data manipulation and data visulisation
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Libraries for data preparation and model building
import scipy as sp
import statsmodels as sm
import sklearn.model_selection as skl
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import Ridge
from sklearn.ensemble import RandomForestRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import r2_score
from sklearn.metrics import mean_squared_error
from sklearn.model_selection import StratifiedKFold
from sklearn.model_selection import KFold
from sklearn.model_selection import train_test_split

# Setting global constants to ensure notebook results are reproducible
PARAMETER_CONSTANT = 42

<a id="two"></a>
## 2. Loading the Data
<a class="anchor" id="1.1"></a>
<a href=#cont>Back to Table of Contents</a>

---
    
| ⚡ Description: Loading the data ⚡ |
| :--------------------------- |
| In this section you are required to load the data from the `df_train` file into a DataFrame. |

---

In [3]:
train_data = pd.read_csv('df_train.csv') # load the train data
test_data = pd.read_csv('df_test.csv')   # load the test data

In [4]:
train_data.columns # overview of train_data columns

Index(['Unnamed: 0', 'time', 'Madrid_wind_speed', 'Valencia_wind_deg',
       'Bilbao_rain_1h', 'Valencia_wind_speed', 'Seville_humidity',
       'Madrid_humidity', 'Bilbao_clouds_all', 'Bilbao_wind_speed',
       'Seville_clouds_all', 'Bilbao_wind_deg', 'Barcelona_wind_speed',
       'Barcelona_wind_deg', 'Madrid_clouds_all', 'Seville_wind_speed',
       'Barcelona_rain_1h', 'Seville_pressure', 'Seville_rain_1h',
       'Bilbao_snow_3h', 'Barcelona_pressure', 'Seville_rain_3h',
       'Madrid_rain_1h', 'Barcelona_rain_3h', 'Valencia_snow_3h',
       'Madrid_weather_id', 'Barcelona_weather_id', 'Bilbao_pressure',
       'Seville_weather_id', 'Valencia_pressure', 'Seville_temp_max',
       'Madrid_pressure', 'Valencia_temp_max', 'Valencia_temp',
       'Bilbao_weather_id', 'Seville_temp', 'Valencia_humidity',
       'Valencia_temp_min', 'Barcelona_temp_max', 'Madrid_temp_max',
       'Barcelona_temp', 'Bilbao_temp_min', 'Bilbao_temp',
       'Barcelona_temp_min', 'Bilbao_temp_max', 'Seville_temp_min',
       'Madrid_temp', 'Madrid_temp_min', 'load_shortfall_3h'],
      dtype='object')

In [5]:
# overview dataset information for train_data
train_data.info

<bound method DataFrame.info of       Unnamed: 0                 time  Madrid_wind_speed Valencia_wind_deg  \
0              0  2015-01-01 03:00:00           0.666667           level_5
1              1  2015-01-01 06:00:00           0.333333          level_10
2              2  2015-01-01 09:00:00           1.000000           level_9
3              3  2015-01-01 12:00:00           1.000000           level_8
4              4  2015-01-01 15:00:00           1.000000           level_7
...          ...                  ...                ...               ...
8758        8758  2017-12-31 09:00:00           1.000000           level_6
8759        8759  2017-12-31 12:00:00           5.000000           level_6
8760        8760  2017-12-31 15:00:00           6.333333           level_9
8761        8761  2017-12-31 18:00:00           7.333333           level_8
8762        8762  2017-12-31 21:00:00           4.333333           level_9

      Bilbao_rain_1h  Valencia_wind_speed  Seville_humidity  Madrid_humidity  \
0                0.0             0.666667         74.333333        64.000000
1                0.0             1.666667         78.333333        64.666667
2                0.0             1.000000         71.333333        64.333333
3                0.0             1.000000         65.333333        56.333333
4                0.0             1.000000         59.000000        57.000000
...              ...                  ...               ...              ...
8758             0.0             2.666667         89.000000        95.666667
8759             0.0             2.000000         82.000000        85.000000
8760             0.4             7.333333         67.666667        71.000000
8761             0.2             7.333333         67.666667        79.000000
8762             0.0             7.000000         78.666667        68.666667

      Bilbao_clouds_all  Bilbao_wind_speed  ...  Madrid_temp_max  \
0              0.000000           1.000000  ...       265.938000
1              0.000000           1.000000  ...       266.386667
2              0.000000           1.000000  ...       272.708667
3              0.000000           1.000000  ...       281.895219
4              2.000000           0.333333  ...       280.678437
...                 ...                ...  ...              ...
8758          56.666667           4.333333  ...       280.816667
8759          26.666667           8.000000  ...       283.483333
8760          63.333333           8.333333  ...       285.150000
8761          63.333333           2.666667  ...       283.483333
8762          20.000000           1.666667  ...       282.150000

      Barcelona_temp  Bilbao_temp_min  Bilbao_temp  Barcelona_temp_min  \
0         281.013000       269.338615   269.338615          281.013000
1         280.561667       270.376000   270.376000          280.561667
2         281.583667       275.027229   275.027229          281.583667
3         283.434104       281.135063   281.135063          283.434104
4         284.213167       282.252063   282.252063          284.213167
...              ...              ...          ...                 ...
8758      281.276667       285.150000   287.573333          280.483333
8759      287.483333       286.483333   288.616667          287.150000
8760      289.816667       283.816667   285.330000          289.150000
8761      287.523333       278.816667   281.410000          286.816667
8762      287.483333       276.816667   281.020000          287.150000

      Bilbao_temp_max  Seville_temp_min Madrid_temp  Madrid_temp_min  \
0          269.338615        274.254667  265.938000       265.938000
1          270.376000        274.945000  266.386667       266.386667
2          275.027229        278.792000  272.708667       272.708667
3          281.135063        285.394000  281.895219       281.895219
4          282.252063        285.513719  280.678437       280.678437
...               ...               ...         ...              ...
8758       290.150000        284.816667  279.686667       278.483333
8759       291.150000        287.150000  282.400000       280.150000
8760       286.816667        289.150000  283.956667       281.150000
8761       284.150000        289.150000  282.666667       280.816667
8762       285.150000        287.483333  281.396667       280.483333

      load_shortfall_3h
0           6715.666667
1           4171.666667
2           4274.666667
3           5075.666667
4           6620.666667
...                 ...
8758         -28.333333
8759        2266.666667
8760         822.000000
8761        -760.000000
8762        2780.666667

[8763 rows x 49 columns]>

In [6]:
# overview dataset information for train_data
train_data.info

<bound method DataFrame.info of       Unnamed: 0                 time  Madrid_wind_speed Valencia_wind_deg  \
0              0  2015-01-01 03:00:00           0.666667           level_5
1              1  2015-01-01 06:00:00           0.333333          level_10
2              2  2015-01-01 09:00:00           1.000000           level_9
3              3  2015-01-01 12:00:00           1.000000           level_8
4              4  2015-01-01 15:00:00           1.000000           level_7
...          ...                  ...                ...               ...
8758        8758  2017-12-31 09:00:00           1.000000           level_6
8759        8759  2017-12-31 12:00:00           5.000000           level_6
8760        8760  2017-12-31 15:00:00           6.333333           level_9
8761        8761  2017-12-31 18:00:00           7.333333           level_8
8762        8762  2017-12-31 21:00:00           4.333333           level_9

      Bilbao_rain_1h  Valencia_wind_speed  Seville_humidity  Madrid_humidity  \
0                0.0             0.666667         74.333333        64.000000
1                0.0             1.666667         78.333333        64.666667
2                0.0             1.000000         71.333333        64.333333
3                0.0             1.000000         65.333333        56.333333
4                0.0             1.000000         59.000000        57.000000
...              ...                  ...               ...              ...
8758             0.0             2.666667         89.000000        95.666667
8759             0.0             2.000000         82.000000        85.000000
8760             0.4             7.333333         67.666667        71.000000
8761             0.2             7.333333         67.666667        79.000000
8762             0.0             7.000000         78.666667        68.666667

      Bilbao_clouds_all  Bilbao_wind_speed  ...  Madrid_temp_max  \
0              0.000000           1.000000  ...       265.938000
1              0.000000           1.000000  ...       266.386667
2              0.000000           1.000000  ...       272.708667
3              0.000000           1.000000  ...       281.895219
4              2.000000           0.333333  ...       280.678437
...                 ...                ...  ...              ...
8758          56.666667           4.333333  ...       280.816667
8759          26.666667           8.000000  ...       283.483333
8760          63.333333           8.333333  ...       285.150000
8761          63.333333           2.666667  ...       283.483333
8762          20.000000           1.666667  ...       282.150000

      Barcelona_temp  Bilbao_temp_min  Bilbao_temp  Barcelona_temp_min  \
0         281.013000       269.338615   269.338615          281.013000
1         280.561667       270.376000   270.376000          280.561667
2         281.583667       275.027229   275.027229          281.583667
3         283.434104       281.135063   281.135063          283.434104
4         284.213167       282.252063   282.252063          284.213167
...              ...              ...          ...                 ...
8758      281.276667       285.150000   287.573333          280.483333
8759      287.483333       286.483333   288.616667          287.150000
8760      289.816667       283.816667   285.330000          289.150000
8761      287.523333       278.816667   281.410000          286.816667
8762      287.483333       276.816667   281.020000          287.150000

      Bilbao_temp_max  Seville_temp_min Madrid_temp  Madrid_temp_min  \
0          269.338615        274.254667  265.938000       265.938000
1          270.376000        274.945000  266.386667       266.386667
2          275.027229        278.792000  272.708667       272.708667
3          281.135063        285.394000  281.895219       281.895219
4          282.252063        285.513719  280.678437       280.678437
...               ...               ...         ...              ...
8758       290.150000        284.816667  279.686667       278.483333
8759       291.150000        287.150000  282.400000       280.150000
8760       286.816667        289.150000  283.956667       281.150000
8761       284.150000        289.150000  282.666667       280.816667
8762       285.150000        287.483333  281.396667       280.483333

      load_shortfall_3h
0           6715.666667
1           4171.666667
2           4274.666667
3           5075.666667
4           6620.666667
...                 ...
8758         -28.333333
8759        2266.666667
8760         822.000000
8761        -760.000000
8762        2780.666667

[8763 rows x 49 columns]>

In [8]:
#checking for missing values

train_data.isnull().T

,0,1,2,3,4,5,6,7,8,9,...,8753,8754,8755,8756,8757,8758,8759,8760,8761,8762
Unnamed: 0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
time,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
Madrid_wind_speed,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
Valencia_wind_deg,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
Bilbao_rain_1h,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
Valencia_wind_speed,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
Seville_humidity,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
Madrid_humidity,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
Bilbao_clouds_all,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
Bilbao_wind_speed,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
Seville_clouds_all,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
Bilbao_wind_deg,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
Barcelona_wind_speed,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
Barcelona_wind_deg,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
Madrid_clouds_all,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
Seville_wind_speed,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
Barcelona_rain_1h,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
Seville_pressure,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
Seville_rain_1h,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
Bilbao_snow_3h,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
Barcelona_pressure,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
Seville_rain_3h,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
Madrid_rain_1h,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
Barcelona_rain_3h,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
Valencia_snow_3h,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
Madrid_weather_id,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
Barcelona_weather_id,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
Bilbao_pressure,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
Seville_weather_id,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
Valencia_pressure,False,False,False,False,True,True,False,False,False,False,...,True,True,True,True,True,True,False,False,False,True
Seville_temp_max,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
Madrid_pressure,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
Valencia_temp_max,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
Valencia_temp,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
Bilbao_weather_id,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
Seville_temp,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
Valencia_humidity,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
Valencia_temp_min,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
Barcelona_temp_max,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
Madrid_temp_max,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
Barcelona_temp,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
Bilbao_temp_min,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
Bilbao_temp,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
Barcelona_temp_min,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
Bilbao_temp_max,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
Seville_temp_min,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
Madrid_temp,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
Madrid_temp_min,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
load_shortfall_3h,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [9]:
train_data.isnull().sum()

Unnamed: 0                 0
time                       0
Madrid_wind_speed          0
Valencia_wind_deg          0
Bilbao_rain_1h             0
Valencia_wind_speed        0
Seville_humidity           0
Madrid_humidity            0
Bilbao_clouds_all          0
Bilbao_wind_speed          0
Seville_clouds_all         0
Bilbao_wind_deg            0
Barcelona_wind_speed       0
Barcelona_wind_deg         0
Madrid_clouds_all          0
Seville_wind_speed         0
Barcelona_rain_1h          0
Seville_pressure           0
Seville_rain_1h            0
Bilbao_snow_3h             0
Barcelona_pressure         0
Seville_rain_3h            0
Madrid_rain_1h             0
Barcelona_rain_3h          0
Valencia_snow_3h           0
Madrid_weather_id          0
Barcelona_weather_id       0
Bilbao_pressure            0
Seville_weather_id         0
Valencia_pressure       2068
Seville_temp_max           0
Madrid_pressure            0
Valencia_temp_max          0
Valencia_temp              0
Bilbao_weather_id          0
Seville_temp               0
Valencia_humidity          0
Valencia_temp_min          0
Barcelona_temp_max         0
Madrid_temp_max            0
Barcelona_temp             0
Bilbao_temp_min            0
Bilbao_temp                0
Barcelona_temp_min         0
Bilbao_temp_max            0
Seville_temp_min           0
Madrid_temp                0
Madrid_temp_min            0
load_shortfall_3h          0
dtype: int64

In [10]:
#checcking non missing values
train_data.notnull()

,Unnamed: 0,time,Madrid_wind_speed,Valencia_wind_deg,Bilbao_rain_1h,Valencia_wind_speed,Seville_humidity,Madrid_humidity,Bilbao_clouds_all,Bilbao_wind_speed,...,Madrid_temp_max,Barcelona_temp,Bilbao_temp_min,Bilbao_temp,Barcelona_temp_min,Bilbao_temp_max,Seville_temp_min,Madrid_temp,Madrid_temp_min,load_shortfall_3h
0,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
1,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
2,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
3,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
4,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8758,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
8759,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
8760,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
8761,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
8762,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True

In [11]:
# the shape of train_data  

train_data.shape

(8763, 49)

<a id="three"></a>
## 3. Exploratory Data Analysis (EDA)
<a class="anchor" id="1.1"></a>
<a href=#cont>Back to Table of Contents</a>

---
    
| ⚡ Description: Exploratory data analysis ⚡ |
| :--------------------------- |
| In this section, you are required to perform an in-depth analysis of all the variables in the DataFrame. |

---

In [12]:
# Read data
train_data.head(3)

,Unnamed: 0,time,Madrid_wind_speed,Valencia_wind_deg,Bilbao_rain_1h,Valencia_wind_speed,Seville_humidity,Madrid_humidity,Bilbao_clouds_all,Bilbao_wind_speed,...,Madrid_temp_max,Barcelona_temp,Bilbao_temp_min,Bilbao_temp,Barcelona_temp_min,Bilbao_temp_max,Seville_temp_min,Madrid_temp,Madrid_temp_min,load_shortfall_3h
0,0,2015-01-01 03:00:00,0.666667,level_5,0.0,0.666667,74.333333,64.000000,0.0,1.0,...,265.938000,281.013000,269.338615,269.338615,281.013000,269.338615,274.254667,265.938000,265.938000,6715.666667
1,1,2015-01-01 06:00:00,0.333333,level_10,0.0,1.666667,78.333333,64.666667,0.0,1.0,...,266.386667,280.561667,270.376000,270.376000,280.561667,270.376000,274.945000,266.386667,266.386667,4171.666667
2,2,2015-01-01 09:00:00,1.000000,level_9,0.0,1.000000,71.333333,64.333333,0.0,1.0,...,272.708667,281.583667,275.027229,275.027229,281.583667,275.027229,278.792000,272.708667,272.708667,4274.666667

In [13]:
#Read the train data in Transpose
"""
The addition of the *T* (transpose)tranforms our data by changing the columns and rows """
train_data.head(10).T

,0,1,2,3,4,5,6,7,8,9
Unnamed: 0,0,1,2,3,4,5,6,7,8,9
time,2015-01-01 03:00:00,2015-01-01 06:00:00,2015-01-01 09:00:00,2015-01-01 12:00:00,2015-01-01 15:00:00,2015-01-01 18:00:00,2015-01-01 21:00:00,2015-01-02 00:00:00,2015-01-02 03:00:00,2015-01-02 06:00:00
Madrid_wind_speed,0.666667,0.333333,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
Valencia_wind_deg,level_5,level_10,level_9,level_8,level_7,level_7,level_8,level_9,level_9,level_9
Bilbao_rain_1h,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Valencia_wind_speed,0.666667,1.666667,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.333333
Seville_humidity,74.333333,78.333333,71.333333,65.333333,59.0,69.666667,83.666667,83.666667,86.0,87.0
Madrid_humidity,64.0,64.666667,64.333333,56.333333,57.0,67.333333,63.333333,64.0,63.333333,63.666667
Bilbao_clouds_all,0.0,0.0,0.0,0.0,2.0,12.333333,16.333333,8.666667,5.333333,15.333333
Bilbao_wind_speed,1.0,1.0,1.0,1.0,0.333333,0.666667,1.0,1.333333,1.0,1.0
Seville_clouds_all,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Bilbao_wind_deg,223.333333,221.0,214.333333,199.666667,185.0,191.333333,210.333333,238.666667,258.333333,255.333333
Barcelona_wind_speed,6.333333,4.0,2.0,2.333333,4.333333,4.666667,3.333333,2.0,1.666667,1.0
Barcelona_wind_deg,42.666667,139.0,326.0,273.0,260.0,254.666667,276.0,310.0,338.0,329.0
Madrid_clouds_all,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Seville_wind_speed,3.333333,3.333333,2.666667,4.0,3.0,2.666667,2.0,2.333333,3.0,3.0
Barcelona_rain_1h,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Seville_pressure,sp25,sp25,sp25,sp25,sp25,sp25,sp25,sp25,sp25,sp25
Seville_rain_1h,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Bilbao_snow_3h,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Barcelona_pressure,1036.333333,1037.333333,1038.0,1037.0,1035.0,1035.666667,1038.0,1037.666667,1037.333333,1038.333333
Seville_rain_3h,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Madrid_rain_1h,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Barcelona_rain_3h,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Valencia_snow_3h,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Madrid_weather_id,800.0,800.0,800.0,800.0,800.0,800.0,800.0,800.0,800.0,800.0
Barcelona_weather_id,800.0,800.0,800.0,800.0,800.0,800.0,800.0,800.0,800.0,800.0
Bilbao_pressure,1035.0,1035.666667,1036.0,1036.0,1035.333333,1035.666667,1036.0,1036.0,1036.666667,1037.0
Seville_weather_id,800.0,800.0,800.0,800.0,800.0,800.0,800.0,800.0,800.0,800.0
Valencia_pressure,1002.666667,1004.333333,1005.333333,1009.0,NaN,NaN,1006.0,1005.666667,1005.333333,1006.333333
Seville_temp_max,274.254667,274.945,278.792,285.394,285.513719,282.077844,277.637,276.457333,276.151667,276.453
Madrid_pressure,971.333333,972.666667,974.0,994.666667,1035.333333,1013.333333,974.333333,974.666667,974.333333,975.333333
Valencia_temp_max,269.888,271.728333,278.008667,284.899552,283.015115,277.622563,272.270333,271.040667,270.535,271.661333
Valencia_temp,269.888,271.728333,278.008667,284.899552,283.015115,277.622563,272.270333,271.040667,270.535,271.661333
Bilbao_weather_id,800.0,800.0,800.0,800.0,800.0,800.666667,800.666667,800.333333,800.0,801.0
Seville_temp,274.254667,274.945,278.792,285.394,285.513719,282.077844,277.637,276.457333,276.151667,276.453
Valencia_humidity,75.666667,71.0,65.666667,54.0,58.333333,72.666667,83.333333,82.0,80.666667,75.333333
Valencia_temp_min,269.888,271.728333,278.008667,284.899552,283.015115,277.622563,272.270333,271.040667,270.535,271.661333
Barcelona_temp_max,281.013,280.561667,281.583667,283.434104,284.213167,284.165625,283.420333,282.474,281.726667,281.803
Madrid_temp_max,265.938,266.386667,272.708667,281.895219,280.678437,274.639229,268.287,266.882333,266.226667,266.878
Barcelona_temp,281.013,280.561667,281.583667,283.434104,284.213167,284.165625,283.420333,282.474,281.726667,281.803
Bilbao_temp_min,269.338615,270.376,275.027229,281.135063,282.252063,277.919,274.295437,272.903167,271.780115,271.673667
Bilbao_temp,269.338615,270.376,275.027229,281.135063,282.252063,277.919,274.295437,272.903167,271.780115,271.673667
Barcelona_temp_min,281.013,280.561667,281.583667,283.434104,284.213167,284.165625,283.420333,282.474,281.726667,281.803
Bilbao_temp_max,269.338615,270.376,275.027229,281.135063,282.252063,277.919,274.295437,272.903167,271.780115,271.673667
Seville_temp_min,274.254667,274.945,278.792,285.394,285.513719,282.077844,277.637,276.457333,276.151667,276.453
Madrid_temp,265.938,266.386667,272.708667,281.895219,280.678437,274.639229,268.287,266.882333,266.226667,266.878
Madrid_temp_min,265.938,266.386667,272.708667,281.895219,280.678437,274.639229,268.287,266.882333,266.226667,266.878
load_shortfall_3h,6715.666667,4171.666667,4274.666667,5075.666667,6620.666667,6842.0,10760.333333,10866.0,-1850.333333,-4002.333333

In [14]:
#checking the shape of the data
train_data.shape

(8763, 49)

In [ ]:
# look at data statistics

In [ ]:
# plot relevant feature interactions

In [ ]:
# evaluate correlation

In [15]:
# have a look at feature distributions

train_data.describe().T

,count,mean,std,min,25%,50%,75%,max
Unnamed: 0,8763.0,4381.000000,2529.804538,0.000000,2190.500000,4381.000000,6571.500000,8.762000e+03
Madrid_wind_speed,8763.0,2.425729,1.850371,0.000000,1.000000,2.000000,3.333333,1.300000e+01
Bilbao_rain_1h,8763.0,0.135753,0.374901,0.000000,0.000000,0.000000,0.100000,3.000000e+00
Valencia_wind_speed,8763.0,2.586272,2.411190,0.000000,1.000000,1.666667,3.666667,5.200000e+01
Seville_humidity,8763.0,62.658793,22.621226,8.333333,44.333333,65.666667,82.000000,1.000000e+02
Madrid_humidity,8763.0,57.414717,24.335396,6.333333,36.333333,58.000000,78.666667,1.000000e+02
Bilbao_clouds_all,8763.0,43.469132,32.551044,0.000000,10.000000,45.000000,75.000000,1.000000e+02
Bilbao_wind_speed,8763.0,1.850356,1.695888,0.000000,0.666667,1.000000,2.666667,1.266667e+01
Seville_clouds_all,8763.0,13.714748,24.272482,0.000000,0.000000,0.000000,20.000000,9.733333e+01
Bilbao_wind_deg,8763.0,158.957511,102.056299,0.000000,73.333333,147.000000,234.000000,3.593333e+02
Barcelona_wind_speed,8763.0,2.870497,1.792197,0.000000,1.666667,2.666667,4.000000,1.266667e+01
Barcelona_wind_deg,8763.0,190.544848,89.077337,0.000000,118.166667,200.000000,260.000000,3.600000e+02
Madrid_clouds_all,8763.0,19.473392,28.053660,0.000000,0.000000,0.000000,33.333333,1.000000e+02
Seville_wind_speed,8763.0,2.425045,1.672895,0.000000,1.000000,2.000000,3.333333,1.166667e+01
Barcelona_rain_1h,8763.0,0.128906,0.634730,0.000000,0.000000,0.000000,0.000000,1.200000e+01
Seville_rain_1h,8763.0,0.039439,0.175857,0.000000,0.000000,0.000000,0.000000,3.000000e+00
Bilbao_snow_3h,8763.0,0.031912,0.557264,0.000000,0.000000,0.000000,0.000000,2.130000e+01
Barcelona_pressure,8763.0,1377.964605,14073.140990,670.666667,1014.000000,1018.000000,1022.000000,1.001411e+06
Seville_rain_3h,8763.0,0.000243,0.003660,0.000000,0.000000,0.000000,0.000000,9.333333e-02
Madrid_rain_1h,8763.0,0.037818,0.152639,0.000000,0.000000,0.000000,0.000000,3.000000e+00
Barcelona_rain_3h,8763.0,0.000439,0.003994,0.000000,0.000000,0.000000,0.000000,9.300000e-02
Valencia_snow_3h,8763.0,0.000205,0.011866,0.000000,0.000000,0.000000,0.000000,7.916667e-01
Madrid_weather_id,8763.0,773.527594,77.313315,211.000000,800.000000,800.000000,800.666667,8.040000e+02
Barcelona_weather_id,8763.0,765.979687,88.142235,200.666667,800.000000,800.333333,801.000000,8.040000e+02
Bilbao_pressure,8763.0,1017.739549,10.046124,971.333333,1013.000000,1019.000000,1024.000000,1.042000e+03
Seville_weather_id,8763.0,774.658818,71.940009,200.000000,800.000000,800.000000,800.000000,8.040000e+02
Valencia_pressure,6695.0,1012.051407,9.506214,972.666667,1010.333333,1015.000000,1018.000000,1.021667e+03
Seville_temp_max,8763.0,297.479527,8.875812,272.063000,291.312750,297.101667,304.150000,3.204833e+02
Madrid_pressure,8763.0,1010.316920,22.198555,927.666667,1012.333333,1017.333333,1022.000000,1.038000e+03
Valencia_temp_max,8763.0,291.337233,7.565692,269.888000,285.550167,291.037000,297.248333,3.142633e+02
Valencia_temp,8763.0,290.592152,7.162274,269.888000,285.150000,290.176667,296.056667,3.104267e+02
Bilbao_weather_id,8763.0,724.722362,115.846537,207.333333,700.333333,800.000000,801.666667,8.040000e+02
Seville_temp,8763.0,293.978903,7.920986,272.063000,288.282917,293.323333,299.620333,3.149767e+02
Valencia_humidity,8763.0,65.247727,19.262322,10.333333,51.333333,67.000000,81.333333,1.000000e+02
Valencia_temp_min,8763.0,289.867648,6.907402,269.888000,284.783333,289.550000,294.820000,3.102720e+02
Barcelona_temp_max,8763.0,291.157644,7.273538,272.150000,285.483333,290.150000,296.855000,3.140767e+02
Madrid_temp_max,8763.0,289.540309,9.752047,264.983333,282.150000,288.116177,296.816667,3.144833e+02
Barcelona_temp,8763.0,289.855459,6.528111,270.816667,284.973443,289.416667,294.909000,3.073167e+02
Bilbao_temp_min,8763.0,285.017973,6.705672,264.483333,280.085167,284.816667,289.816667,3.098167e+02
Bilbao_temp,8763.0,286.422929,6.818682,267.483333,281.374167,286.158333,291.034167,3.107100e+02
Barcelona_temp_min,8763.0,288.447422,6.102593,269.483333,284.150000,288.150000,292.966667,3.048167e+02
Bilbao_temp_max,8763.0,287.966027,7.105590,269.063000,282.836776,287.630000,292.483333,3.179667e+02
Seville_temp_min,8763.0,291.633356,8.178220,270.150000,285.816667,290.816667,297.150000,3.148167e+02
Madrid_temp,8763.0,288.419439,9.346796,264.983333,281.404281,287.053333,295.154667,3.131333e+02
Madrid_temp_min,8763.0,287.202203,9.206237,264.983333,280.299167,286.083333,293.884500,3.103833e+02
load_shortfall_3h,8763.0,10673.857612,5218.046404,-6618.000000,7390.333333,11114.666667,14498.166667,3.190400e+04

In [16]:
#check for skewness

train_data.skew(numeric_only=True)

Unnamed: 0               0.000000
Madrid_wind_speed        1.441144
Bilbao_rain_1h           5.222802
Valencia_wind_speed      3.499637
Seville_humidity        -0.310175
Madrid_humidity         -0.057378
Bilbao_clouds_all       -0.053085
Bilbao_wind_speed        1.716914
Seville_clouds_all       1.814452
Bilbao_wind_deg          0.226927
Barcelona_wind_speed     1.057331
Barcelona_wind_deg      -0.180001
Madrid_clouds_all        1.246745
Seville_wind_speed       1.151006
Barcelona_rain_1h        8.726988
Seville_rain_1h          8.067341
Bilbao_snow_3h          26.177568
Barcelona_pressure      57.979664
Seville_rain_3h         19.342574
Madrid_rain_1h           7.074308
Barcelona_rain_3h       12.696605
Valencia_snow_3h        63.298084
Madrid_weather_id       -3.107722
Barcelona_weather_id    -2.584011
Bilbao_pressure         -0.999642
Seville_weather_id      -3.275574
Valencia_pressure       -1.705162
Seville_temp_max        -0.033931
Madrid_pressure         -1.850768
Valencia_temp_max        0.082672
Valencia_temp            0.057476
Bilbao_weather_id       -1.234844
Seville_temp             0.157238
Valencia_humidity       -0.305757
Valencia_temp_min        0.081832
Barcelona_temp_max       0.276925
Madrid_temp_max          0.298707
Barcelona_temp           0.128095
Bilbao_temp_min          0.194912
Bilbao_temp              0.293686
Barcelona_temp_min      -0.018057
Bilbao_temp_max          0.393932
Seville_temp_min         0.265482
Madrid_temp              0.304123
Madrid_temp_min          0.275083
load_shortfall_3h       -0.384847
dtype: float64

In [ ]:
#find numerical and categorical values
train_data.info()

In [ ]:
# plotting distributions of all the features in train
train_data.hist(bins=50, figsize=(30,30), color = 'tab:orange')
plt.show()

In [ ]:
#correlation plot heatmap
train_corr=train_data.corr().T
plt.figure(figsize=(40,42))

# Mask top half of matrix as it contains redunant info
mask = np.zeros_like(train_corr)
mask[np.triu_indices_from(mask)] = True

sns.heatmap(train_corr,annot=True, vmin=-1, vmax=1, cmap='autumn', linewidth

<a id="four"></a>
## 4. Data Engineering
<a class="anchor" id="1.1"></a>
<a href=#cont>Back to Table of Contents</a>

---
    
| ⚡ Description: Data engineering ⚡ |
| :--------------------------- |
| In this section you are required to: clean the dataset, and possibly create new features - as identified in the EDA phase. |

---

In [ ]:
# remove missing values/ features

In [ ]:
# create new features

In [ ]:
# engineer existing features

<a id="five"></a>
## 6. Modelling
<a class="anchor" id="1.1"></a>
<a href=#cont>Back to Table of Contents</a>

---
    
| ⚡ Description: Modelling ⚡ |
| :--------------------------- |
| In this section, you are required to create one or more regression models that are able to accurately predict the thee hour load shortfall. |

---

In [ ]:
# split data

In [ ]:
# create targets and features dataset

In [ ]:
# create one or more ML models

In [ ]:
# evaluate one or more ML models

In [ ]:
#Separate the feature variables (X) and the target variable (y) in the train dataset
y = df_clean_train[:len(df)][['load_shortfall_3h']]
x = df_clean_train[:len(df)].drop('load_shortfall_3h' ,axis=1)

In [ ]:
# Splitting the train dataset into train and validation sets
x_train, x_val, y_train, y_val = train_test_split(x, y, test_size=0.2, random_state=42)

# X_train: Independent variables for training
# X_val: Independent variables for validation
# y_train: Target variable for training
# y_val: Target variable for validation

# Creating different models

In [ ]:
#create a linear regression model
lr = LinearRegression()

In [ ]:
#Create an instance of the Ridge regression model. You can specify the regularization strength (alpha) as a parameter. Higher alpha values will result in stronger regularization.
#Create a ridge model
ridge = Ridge(alpha=1.0)

In [ ]:
# Create a Random Forest model with a specific random state
rf = RandomForestRegressor(n_estimators=100, random_state=42)

In [ ]:
# Create a Decision Tree model
dt = DecisionTreeRegressor(max_depth=5, min_samples_split=2)

In [ ]:
#Fit the above created models

In [ ]:
# Fit the linear regression model to the training data
lr.fit(x_train, y_train)

In [ ]:
# Fit the ridge model to the training data
ridge.fit(x_train, y_train)

In [ ]:
# Fit the random forest model to the training data
rf.fit(x_train, y_train.values.ravel())

In [ ]:
# Fit the decision tree model to the training data
dt.fit(x_train, y_train)

In [ ]:
### Fit the decision tree model to the training data
dt.fit(x_train, y_train)

# Make predictions on the validation set

In [ ]:
#Linear regression
y_pred_val_lr = lr.predict(x_val)

In [ ]:
#Ridge regression
y_pred_val_rd = ridge.predict(x_val)

In [ ]:
#Random Forest
y_pred_val_rf = rf.predict(x_val)

In [ ]:
#Decision Tree
y_pred_val_dt = dt.predict(x_val)

<a id="six"></a>
## 7. Model Performance
<a class="anchor" id="1.1"></a>
<a href=#cont>Back to Table of Contents</a>

---
    
| ⚡ Description: Model performance ⚡ |
| :--------------------------- |
| In this section you are required to compare the relative performance of the various trained ML models on a holdout dataset and comment on what model is the best and why. |

---

In [ ]:
# Compare model performance

In [ ]:
# Choose best model and motivate why it is the best choice

In [ ]:
# Check each model's performance using RMSE and R-squared (R^2)

In [ ]:
# MODEL PERFOMANCE OF EACH MODEL ON THE VALIDATION SET

In [ ]:
def rmse(y_val, y_predict):
    return np.sqrt(mean_squared_error(y_val, y_predict))

In [ ]:
# Calculate the RMSE on the validation set
rmse = np.sqrt(mean_squared_error(y_val, y_pred_val_lr))
print("Validation Set RMSE Linear regression(LR):", rmse)

# Calculate the RMSE on the validation set
rmse = np.sqrt(mean_squared_error(y_val, y_pred_val_rd))
print("Validation Set RMSE Linear regression (RD):", rmse)

# Calculate the RMSE on the validation set
rmse = np.sqrt(mean_squared_error(y_val, y_pred_val_rf))
print("Validation Set RMSE Linear regression(RF):", rmse)

# Calculate the RMSE on the validation set
rmse = np.sqrt(mean_squared_error(y_val, y_pred_val_dt))
print("Validation Set RMSE Linear regression(DT):", rmse)

In [ ]:
r2_score(y_val, y_pred_val_lr)

In [ ]:
r2_score(y_val, y_pred_val_rd)

In [ ]:
r2_score(y_val, y_pred_val_rf)

In [ ]:
r2_score(y_val, y_pred_val_dt)

In [ ]:
x_test = df_clean_test

In [ ]:
preds = rf.predict(x_test)

In [ ]:
x_train = df_clean_train[:len(df)].drop('load_shortfall_3h', axis=1)
x_test = df_clean_train[len(df):].drop('load_shortfall_3h' , axis =1)

In [ ]:
daf = pd.DataFrame(preds, columns=['load_shortfall_3h'])
daf.head()

In [ ]:
output = pd.DataFrame({'time': df_test['time']})
submission = output.join(daf)
submission.to_csv('submission.csv', index=False)

In [ ]:
submission

<a id="seven"></a>
## 8. Model Explanations
<a class="anchor" id="1.1"></a>
<a href=#cont>Back to Table of Contents</a>

---
    
| ⚡ Description: Model explanation ⚡ |
| :--------------------------- |
| In this section, you are required to discuss how the best performing model works in a simple way so that both technical and non-technical stakeholders can grasp the intuition behind the model's inner workings. |

---

In [ ]:
# discuss chosen methods logic

# 9. Saving The Model

In [ ]:
import pickle

model_save_path = "rf_model.pkl"
with open(model_save_path,'wb') as file:
    pickle.dump(rf,file)

In [ ]:
model_load_path = "mlr_model.pkl"
with open(model_load_path,'rb') as file:
    unpickled_model = pickle.load(file)